apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-kafka
  namespace: posco-app
  labels:
    app: cp-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-kafka
  template:
    metadata:
      labels:
        app: cp-kafka
    spec:
      containers:
      - name: cp-kafka
        image: 088736462092.dkr.ecr.ap-south-1.amazonaws.com/posco-ecr-test:cp-kafka
        imagePullPolicy: Always
        ports:
        - containerPort: 9092  # Kafka internal listener port
        - containerPort: 9094  # Kafka external listener port
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "cp-zookeeper:2181"  # Kafka connects to Zookeeper
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://cp-kafka:9092,EXTERNAL://cp-kafka:9094"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
      imagePullSecrets:
        - name: ecr-creds
---
apiVersion: v1
kind: Service
metadata:
  name: cp-kafka
  namespace: posco-app
spec:
  selector:
    app: cp-kafka
  ports:
  - name: internal
    protocol: TCP
    port: 9092  # Exposing internal Kafka port
    targetPort: 9092
  - name: external
    protocol: TCP
    port: 9094  # Exposing external Kafka port
    targetPort: 9094
