apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-redis
  namespace: posco-app
  labels:
    app: cp-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-redis
  template:
    metadata:
      labels:
        app: cp-redis
    spec:
      containers:
        - name: cp-cp-redis
          image: 088736462092.dkr.ecr.ap-south-1.amazonaws.com/posco-ecr:cp-redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: cp-redis
  namespace: posco-app
spec:
  selector:
    app: cp-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
